export interface BankCriteria {
  minIncome: number
  minCreditScore: number
  maxAge: number
  minAge: number
  maxLoanAmount: number
  minLoanAmount: number
  maxLTVRatio: number // Loan to Value ratio
  maxEMIRatio: number // EMI to Income ratio
  acceptsSelfEmployed: boolean
  acceptsNoCredit: boolean
  propertyAreas: string[]
  requiredDocuments: string[]
  processingTime: string
  interestRateRange: {
    min: number
    max: number
  }
}

export interface IndianBank {
  id: string
  name: string
  type: "Public Sector" | "Private Sector" | "NBFC" | "Cooperative"
  established: number
  headquarters: string
  website: string
  customerCare: string
  homeLoanCriteria: BankCriteria
  personalLoanCriteria: BankCriteria
  businessLoanCriteria: BankCriteria
  specialPrograms: string[]
  strengths: string[]
  digitalServices: string[]
  branches: number
  rating: number
}

export const indianBanks: IndianBank[] = [
  {
    id: "sbi",
    name: "State Bank of India",
    type: "Public Sector",
    established: 1955,
    headquarters: "Mumbai, Maharashtra",
    website: "https://sbi.co.in",
    customerCare: "1800-11-2211",
    homeLoanCriteria: {
      minIncome: 25000,
      minCreditScore: 650,
      maxAge: 65,
      minAge: 21,
      maxLoanAmount: 50000000,
      minLoanAmount: 100000,
      maxLTVRatio: 90,
      maxEMIRatio: 50,
      acceptsSelfEmployed: true,
      acceptsNoCredit: true,
      propertyAreas: ["Urban", "Semiurban", "Rural"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof", "Property Documents"],
      processingTime: "7-15 days",
      interestRateRange: { min: 8.5, max: 9.5 },
    },
    personalLoanCriteria: {
      minIncome: 20000,
      minCreditScore: 650,
      maxAge: 60,
      minAge: 21,
      maxLoanAmount: 2000000,
      minLoanAmount: 50000,
      maxLTVRatio: 0,
      maxEMIRatio: 50,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban", "Rural"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof"],
      processingTime: "3-7 days",
      interestRateRange: { min: 10.5, max: 15.5 },
    },
    businessLoanCriteria: {
      minIncome: 50000,
      minCreditScore: 700,
      maxAge: 65,
      minAge: 25,
      maxLoanAmount: 100000000,
      minLoanAmount: 500000,
      maxLTVRatio: 0,
      maxEMIRatio: 40,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Business Proof", "Income Proof", "Identity Proof", "Financial Statements"],
      processingTime: "15-30 days",
      interestRateRange: { min: 9.5, max: 12.5 },
    },
    specialPrograms: ["Women Borrower Scheme", "Rural Housing Scheme", "Green Home Loan"],
    strengths: ["Largest branch network", "Government backing", "Competitive rates"],
    digitalServices: ["YONO App", "Internet Banking", "Mobile Banking"],
    branches: 22000,
    rating: 4.2,
  },
  {
    id: "hdfc",
    name: "HDFC Bank",
    type: "Private Sector",
    established: 1994,
    headquarters: "Mumbai, Maharashtra",
    website: "https://hdfcbank.com",
    customerCare: "1800-266-4332",
    homeLoanCriteria: {
      minIncome: 30000,
      minCreditScore: 700,
      maxAge: 65,
      minAge: 21,
      maxLoanAmount: 75000000,
      minLoanAmount: 100000,
      maxLTVRatio: 90,
      maxEMIRatio: 50,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof", "Property Documents"],
      processingTime: "5-10 days",
      interestRateRange: { min: 8.75, max: 9.75 },
    },
    personalLoanCriteria: {
      minIncome: 25000,
      minCreditScore: 700,
      maxAge: 60,
      minAge: 21,
      maxLoanAmount: 4000000,
      minLoanAmount: 50000,
      maxLTVRatio: 0,
      maxEMIRatio: 50,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof"],
      processingTime: "2-5 days",
      interestRateRange: { min: 10.75, max: 21.0 },
    },
    businessLoanCriteria: {
      minIncome: 75000,
      minCreditScore: 750,
      maxAge: 65,
      minAge: 25,
      maxLoanAmount: 200000000,
      minLoanAmount: 1000000,
      maxLTVRatio: 0,
      maxEMIRatio: 40,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Business Proof", "Income Proof", "Identity Proof", "Financial Statements"],
      processingTime: "10-20 days",
      interestRateRange: { min: 10.0, max: 14.0 },
    },
    specialPrograms: ["Women Power Scheme", "Smart EMI", "Top-up Loans"],
    strengths: ["Fast processing", "Digital services", "Premium customer service"],
    digitalServices: ["NetBanking", "MobileBanking", "PayZapp"],
    branches: 6000,
    rating: 4.5,
  },
  {
    id: "icici",
    name: "ICICI Bank",
    type: "Private Sector",
    established: 1994,
    headquarters: "Mumbai, Maharashtra",
    website: "https://icicibank.com",
    customerCare: "1860-120-7777",
    homeLoanCriteria: {
      minIncome: 25000,
      minCreditScore: 700,
      maxAge: 65,
      minAge: 23,
      maxLoanAmount: 50000000,
      minLoanAmount: 100000,
      maxLTVRatio: 90,
      maxEMIRatio: 50,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof", "Property Documents"],
      processingTime: "7-12 days",
      interestRateRange: { min: 8.7, max: 9.5 },
    },
    personalLoanCriteria: {
      minIncome: 20000,
      minCreditScore: 700,
      maxAge: 60,
      minAge: 23,
      maxLoanAmount: 2500000,
      minLoanAmount: 50000,
      maxLTVRatio: 0,
      maxEMIRatio: 50,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof"],
      processingTime: "3-7 days",
      interestRateRange: { min: 10.5, max: 19.0 },
    },
    businessLoanCriteria: {
      minIncome: 60000,
      minCreditScore: 750,
      maxAge: 65,
      minAge: 25,
      maxLoanAmount: 150000000,
      minLoanAmount: 750000,
      maxLTVRatio: 0,
      maxEMIRatio: 40,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Business Proof", "Income Proof", "Identity Proof", "Financial Statements"],
      processingTime: "12-25 days",
      interestRateRange: { min: 9.75, max: 13.5 },
    },
    specialPrograms: ["Instant Home Loan", "Flexi Pay Home Loan", "Women Entrepreneur Loans"],
    strengths: ["Technology innovation", "Quick approvals", "Flexible repayment options"],
    digitalServices: ["iMobile Pay", "Internet Banking", "Video Banking"],
    branches: 5200,
    rating: 4.3,
  },
  {
    id: "axis",
    name: "Axis Bank",
    type: "Private Sector",
    established: 1993,
    headquarters: "Mumbai, Maharashtra",
    website: "https://axisbank.com",
    customerCare: "1860-419-5555",
    homeLoanCriteria: {
      minIncome: 30000,
      minCreditScore: 700,
      maxAge: 65,
      minAge: 21,
      maxLoanAmount: 50000000,
      minLoanAmount: 100000,
      maxLTVRatio: 90,
      maxEMIRatio: 50,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof", "Property Documents"],
      processingTime: "7-14 days",
      interestRateRange: { min: 8.75, max: 9.65 },
    },
    personalLoanCriteria: {
      minIncome: 25000,
      minCreditScore: 700,
      maxAge: 60,
      minAge: 21,
      maxLoanAmount: 3500000,
      minLoanAmount: 50000,
      maxLTVRatio: 0,
      maxEMIRatio: 50,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof"],
      processingTime: "2-5 days",
      interestRateRange: { min: 10.49, max: 22.0 },
    },
    businessLoanCriteria: {
      minIncome: 50000,
      minCreditScore: 750,
      maxAge: 65,
      minAge: 25,
      maxLoanAmount: 100000000,
      minLoanAmount: 500000,
      maxLTVRatio: 0,
      maxEMIRatio: 40,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Business Proof", "Income Proof", "Identity Proof", "Financial Statements"],
      processingTime: "10-20 days",
      interestRateRange: { min: 10.25, max: 14.0 },
    },
    specialPrograms: ["Shubh Aarambh Home Loan", "Power Salute for Defense Personnel", "Sarva Shakti for Women"],
    strengths: ["Personalized service", "Flexible terms", "Strong digital platform"],
    digitalServices: ["Axis Mobile", "Internet Banking", "WhatsApp Banking"],
    branches: 4700,
    rating: 4.1,
  },
  {
    id: "pnb",
    name: "Punjab National Bank",
    type: "Public Sector",
    established: 1894,
    headquarters: "New Delhi",
    website: "https://pnbindia.in",
    customerCare: "1800-180-2222",
    homeLoanCriteria: {
      minIncome: 20000,
      minCreditScore: 650,
      maxAge: 65,
      minAge: 18,
      maxLoanAmount: 30000000,
      minLoanAmount: 100000,
      maxLTVRatio: 90,
      maxEMIRatio: 50,
      acceptsSelfEmployed: true,
      acceptsNoCredit: true,
      propertyAreas: ["Urban", "Semiurban", "Rural"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof", "Property Documents"],
      processingTime: "10-20 days",
      interestRateRange: { min: 8.4, max: 9.15 },
    },
    personalLoanCriteria: {
      minIncome: 15000,
      minCreditScore: 650,
      maxAge: 60,
      minAge: 21,
      maxLoanAmount: 1000000,
      minLoanAmount: 25000,
      maxLTVRatio: 0,
      maxEMIRatio: 50,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban", "Rural"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof"],
      processingTime: "5-10 days",
      interestRateRange: { min: 9.95, max: 14.45 },
    },
    businessLoanCriteria: {
      minIncome: 40000,
      minCreditScore: 700,
      maxAge: 65,
      minAge: 25,
      maxLoanAmount: 50000000,
      minLoanAmount: 500000,
      maxLTVRatio: 0,
      maxEMIRatio: 40,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban", "Rural"],
      requiredDocuments: ["Business Proof", "Income Proof", "Identity Proof", "Financial Statements"],
      processingTime: "15-30 days",
      interestRateRange: { min: 9.25, max: 12.0 },
    },
    specialPrograms: ["PNB Ghar", "Mahila Udyamita Scheme", "Rozgar Scheme"],
    strengths: ["Wide rural presence", "Government support", "Low interest rates"],
    digitalServices: ["PNB ONE", "Internet Banking", "Mobile Banking"],
    branches: 11000,
    rating: 3.9,
  },
  {
    id: "kotak",
    name: "Kotak Mahindra Bank",
    type: "Private Sector",
    established: 2003,
    headquarters: "Mumbai, Maharashtra",
    website: "https://kotak.com",
    customerCare: "1860-266-2666",
    homeLoanCriteria: {
      minIncome: 35000,
      minCreditScore: 750,
      maxAge: 65,
      minAge: 21,
      maxLoanAmount: 100000000,
      minLoanAmount: 500000,
      maxLTVRatio: 90,
      maxEMIRatio: 50,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof", "Property Documents"],
      processingTime: "5-10 days",
      interestRateRange: { min: 8.7, max: 9.4 },
    },
    personalLoanCriteria: {
      minIncome: 30000,
      minCreditScore: 750,
      maxAge: 60,
      minAge: 21,
      maxLoanAmount: 5000000,
      minLoanAmount: 100000,
      maxLTVRatio: 0,
      maxEMIRatio: 50,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof"],
      processingTime: "2-4 days",
      interestRateRange: { min: 10.99, max: 20.0 },
    },
    businessLoanCriteria: {
      minIncome: 100000,
      minCreditScore: 750,
      maxAge: 65,
      minAge: 25,
      maxLoanAmount: 500000000,
      minLoanAmount: 2000000,
      maxLTVRatio: 0,
      maxEMIRatio: 40,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Business Proof", "Income Proof", "Identity Proof", "Financial Statements"],
      processingTime: "7-15 days",
      interestRateRange: { min: 11.0, max: 15.0 },
    },
    specialPrograms: ["Express Home Loan", "Women Achiever Program", "NRI Home Loans"],
    strengths: ["Premium banking", "Quick processing", "High loan amounts"],
    digitalServices: ["Kotak Mobile Banking", "Net Banking", "WhatsApp Banking"],
    branches: 1600,
    rating: 4.4,
  },
  {
    id: "canara",
    name: "Canara Bank",
    type: "Public Sector",
    established: 1906,
    headquarters: "Bengaluru, Karnataka",
    website: "https://canarabank.com",
    customerCare: "1800-425-0018",
    homeLoanCriteria: {
      minIncome: 20000,
      minCreditScore: 650,
      maxAge: 65,
      minAge: 18,
      maxLoanAmount: 20000000,
      minLoanAmount: 100000,
      maxLTVRatio: 90,
      maxEMIRatio: 50,
      acceptsSelfEmployed: true,
      acceptsNoCredit: true,
      propertyAreas: ["Urban", "Semiurban", "Rural"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof", "Property Documents"],
      processingTime: "10-15 days",
      interestRateRange: { min: 8.4, max: 9.05 },
    },
    personalLoanCriteria: {
      minIncome: 15000,
      minCreditScore: 650,
      maxAge: 60,
      minAge: 21,
      maxLoanAmount: 1500000,
      minLoanAmount: 25000,
      maxLTVRatio: 0,
      maxEMIRatio: 50,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban", "Rural"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof"],
      processingTime: "7-12 days",
      interestRateRange: { min: 10.75, max: 15.7 },
    },
    businessLoanCriteria: {
      minIncome: 35000,
      minCreditScore: 700,
      maxAge: 65,
      minAge: 25,
      maxLoanAmount: 75000000,
      minLoanAmount: 500000,
      maxLTVRatio: 0,
      maxEMIRatio: 40,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban", "Rural"],
      requiredDocuments: ["Business Proof", "Income Proof", "Identity Proof", "Financial Statements"],
      processingTime: "15-25 days",
      interestRateRange: { min: 9.4, max: 12.25 },
    },
    specialPrograms: ["Can Sahaj", "Mahila Shakti Scheme", "Canara Robosub"],
    strengths: ["Strong South India presence", "Agricultural lending", "Competitive rates"],
    digitalServices: ["Canara ai1 Mobile", "Internet Banking", "UPI"],
    branches: 9500,
    rating: 4.0,
  },
  {
    id: "bajaj",
    name: "Bajaj Finserv",
    type: "NBFC",
    established: 2007,
    headquarters: "Pune, Maharashtra",
    website: "https://bajajfinserv.in",
    customerCare: "1800-103-0003",
    homeLoanCriteria: {
      minIncome: 25000,
      minCreditScore: 700,
      maxAge: 70,
      minAge: 23,
      maxLoanAmount: 50000000,
      minLoanAmount: 600000,
      maxLTVRatio: 90,
      maxEMIRatio: 60,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof", "Property Documents"],
      processingTime: "3-7 days",
      interestRateRange: { min: 8.5, max: 11.5 },
    },
    personalLoanCriteria: {
      minIncome: 20000,
      minCreditScore: 700,
      maxAge: 65,
      minAge: 23,
      maxLoanAmount: 2500000,
      minLoanAmount: 50000,
      maxLTVRatio: 0,
      maxEMIRatio: 60,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Income Proof", "Identity Proof", "Address Proof"],
      processingTime: "1-3 days",
      interestRateRange: { min: 11.0, max: 25.0 },
    },
    businessLoanCriteria: {
      minIncome: 50000,
      minCreditScore: 750,
      maxAge: 65,
      minAge: 25,
      maxLoanAmount: 50000000,
      minLoanAmount: 1000000,
      maxLTVRatio: 0,
      maxEMIRatio: 50,
      acceptsSelfEmployed: true,
      acceptsNoCredit: false,
      propertyAreas: ["Urban", "Semiurban"],
      requiredDocuments: ["Business Proof", "Income Proof", "Identity Proof", "Financial Statements"],
      processingTime: "5-10 days",
      interestRateRange: { min: 12.0, max: 18.0 },
    },
    specialPrograms: ["Instant Approval", "Flexi Personal Loan", "Business Loan Express"],
    strengths: ["Quick processing", "Minimal documentation", "Flexible terms"],
    digitalServices: ["Bajaj Finserv App", "Online Portal", "Digital KYC"],
    branches: 1400,
    rating: 4.2,
  },
]

export function getBankById(id: string): IndianBank | undefined {
  return indianBanks.find((bank) => bank.id === id)
}

export function getBanksByType(type: IndianBank["type"]): IndianBank[] {
  return indianBanks.filter((bank) => bank.type === type)
}

export function getAllBankNames(): string[] {
  return indianBanks.map((bank) => bank.name)
}
